name: Sync LeetCode

on:
  workflow_dispatch: # Allows you to run this manually for the initial history import
  schedule:
    - cron: "0 20 * * *" # Runs every day at 12:00 PM (Noon) UTC and 1 hour before midnight in gmt +3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        # REPLACE THE HASH BELOW with the one you copied in Step 1. 
        # The hash below is the official v1.7 release hash, which is currently safe.
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions # Keeps your repo organized
          verbose: true
          commit-header: "[LeetCode Sync]"
